version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  web:
    build:
      context: .
      args:
        ENV: prod
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  test_db:
    image: postgres:11
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  test:
    build:
      context: .
      args:
        ENV: test
    volumes:
      - ./tests:/app/tests
    command: bash -c "sleep 10 && alembic upgrade head && pytest -vv"
    env_file:
      - .env.test
    depends_on:
      - test_db

networks:
  default:
    external:
      name: network
