version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DB_HOST: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  default:
    name: network
